# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl40BzMlcMXK6rvf8BEMSb-go66h0v2z
"""

import os
import csv
import io
import math
from datetime import datetime, timezone
import time
import feedparser
import requests
from google import genai
from google.genai.errors import APIError  # Added to handle Gemini specific errors
import yfinance as yf


# Get secrets from GitHub Actions
BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_ID = os.getenv("CHANNEL_ID")
GEMINI_KEY = os.getenv("GEMINI_KEY")
CHANNEL_ID_2 = os.getenv("CHANNEL_ID_2")


RSS_FEEDS = [
    # 📊 MarketWatch (official RSS)
    "https://feeds.marketwatch.com/marketwatch/topstories/",

    # ₿ CoinDesk (crypto)
    "https://www.coindesk.com/arc/outboundfeeds/rss/",

    # 📈 Investing.com (official RSS)
    "https://www.investing.com/rss/news.rss",
    "https://www.investing.com/rss/news_25.rss",  # economic calendar / macro focus

    # 📰 Reuters (official but limited RSS)
    "https://feeds.reuters.com/reuters/businessNews",
    "https://feeds.reuters.com/reuters/globalmarketsNews",

    # 📊 Yahoo Finance (official RSS)
    "https://finance.yahoo.com/news/rssindex",
    "https://feeds.finance.yahoo.com/rss/2.0/headline",

    # 🏦 Financial Times (official section RSS)
    "https://www.ft.com/world?format=rss",
    "https://www.ft.com/markets?format=rss",
    "https://www.ft.com/global-economy?format=rss",

    # 🏛 Bloomberg (⚠️ via Google News RSS workaround)
    "https://news.google.com/rss/search?q=site:bloomberg.com+markets",
    "https://news.google.com/rss/search?q=site:bloomberg.com+economy",

    # 📰 Wall Street Journal (⚠️ limited + workaround)
    "https://wsj.com/xml/rss/3_7014.xml",
    "https://wsj.com/xml/rss/3_7031.xml",
    "https://news.google.com/rss/search?q=site:wsj.com+markets",

    # 📊 Morningstar (no official RSS → Google News workaround)
    "https://news.google.com/rss/search?q=site:morningstar.com+stocks",
    "https://news.google.com/rss/search?q=site:morningstar.com+fund",

    # 📉 Barron's (no official RSS → workaround)
    "https://news.google.com/rss/search?q=site:barrons.com+markets",

    # 🌍 The Economist (no official RSS → workaround)
    "https://news.google.com/rss/search?q=site:economist.com+economy",

    # 💱 Forex Factory (VERY IMPORTANT for FX + macro)
    "https://www.forexfactory.com/news-feed",
    "https://www.forexfactory.com/calendar"
]


def is_valid_url(url):
    return url and url.startswith("http") and "news.google.com" not in url


def get_news():
    articles = []

    for feed_url in RSS_FEEDS:
        try:
            feed = feedparser.parse(feed_url)

            if not hasattr(feed, "entries"):
                continue

            for entry in feed.entries[:3]:
                if hasattr(entry, "title") and hasattr(entry, "link"):
                    if is_valid_url(entry.link):
                        articles.append({
                            "title": entry.title,
                            "summary": getattr(entry, "summary", ""),
                            "link": entry.link
                        })

        except Exception as e:
            print(f"RSS failed: {feed_url} -> {e}")

    return articles


def get_change(symbol):
    """Change between the latest two available Yahoo daily closing values."""
    hist = yf.Ticker(symbol).history(period="1mo", timeout=20)
    if hist.empty or "Close" not in hist:
        return None

    closes = hist["Close"].dropna().sort_index()
    if len(closes) < 2:
        return None

    last, prev = float(closes.iloc[-1]), float(closes.iloc[-2])
    if not math.isfinite(last) or not math.isfinite(prev) or prev <= 0:
        return None
    return last, ((last - prev) / prev) * 100


def format_change(change, unit="%", decimals=2):
    # Round before choosing the arrow to avoid negative zero or tiny-move arrows.
    value = round(change, decimals)
    number = f"{value:+.{decimals}f}" if value else f"{0:.{decimals}f}"
    separator = " " if unit == "bps" else ""
    return f"{number}{separator}{unit}""


def get_treasury_yields():
    """Fetch all four daily par yields from one official Treasury series.

    Source and methodology:
    https://home.treasury.gov/policy-issues/financing-the-government/interest-rate-statistics
    Values are percentages; a 0.01 percentage-point change equals 1 basis point.
    These are daily par yields, not live quotes for individual Treasury bonds.
    """
    today = datetime.now(timezone.utc).date()
    columns = ("2 Yr", "5 Yr", "10 Yr", "30 Yr")
    observations = {}

    # At New Year, the previous comparison observation may be in last year's file.
    for year in (today.year, today.year - 1):
        url = (
            "https://home.treasury.gov/resource-center/data-chart-center/"
            f"interest-rates/daily-treasury-rates.csv/{year}/all"
        )
        response = requests.get(
            url,
            params={
                "_format": "csv",
                "field_tdr_date_value": year,
                "type": "daily_treasury_yield_curve",
            },
            timeout=20,
        )
        response.raise_for_status()
        reader = csv.DictReader(io.StringIO(response.content.decode("utf-8-sig")))
        if not reader.fieldnames or not {"Date", *columns}.issubset(reader.fieldnames):
            raise ValueError("Treasury returned an unexpected CSV format")

        for row in reader:
            try:
                day = datetime.strptime(row["Date"], "%m/%d/%Y").date()
                values = {column: float(row[column]) for column in columns}
            except (TypeError, ValueError):
                continue
            if day <= today and all(math.isfinite(v) for v in values.values()):
                observations[day] = values
        if len(observations) >= 2:
            break

    if len(observations) < 2:
        return None

    previous_day, latest_day = sorted(observations)[-2:]
    return latest_day, {
        column: (
            observations[latest_day][column],
            (observations[latest_day][column] - observations[previous_day][column]) * 100,
        )
        for column in columns
    }


def get_market_snapshot():
    lines = ["📊 Market Snapshot", "", "📊 Key Market Prices"]
    assets = [
        ("🥇 Gold futures", "GC=F", "${:,.2f}"),
        ("💻 Nasdaq 100", "^NDX", "{:,.2f}"),
        ("📈 S&P 500", "^GSPC", "{:,.2f}"),
        ("🏭 Dow Jones", "^DJI", "{:,.2f}"),
        ("🛢️ Brent futures", "BZ=F", "${:,.2f}"),
        ("💵 US Dollar Index (DXY)", "DX-Y.NYB", "{:.3f}"),
        ("₿ Bitcoin", "BTC-USD", "${:,.2f}"),
        ("🔷 Ethereum", "ETH-USD", "${:,.2f}"),
    ]

    def add_quote(name, ticker, fmt):
        try:
            result = get_change(ticker)
            if result is not None:
                price, change = result
                lines.append(f"{name}: {fmt.format(price)} ({format_change(change)})")
                return
        except Exception as e:
            print(f"{ticker} failed: {e}")
        lines.append(f"{name}: unavailable")

    for name, ticker, fmt in assets:
        add_quote(name, ticker, fmt)

    lines.extend(["", "🇺🇸 US Treasury Yields"])
    try:
        result = get_treasury_yields()
        if result is None:
            lines.append("Treasury yields unavailable")
        else:
            as_of, yields = result
            lines.append(f"Daily par yields • {as_of:%Y-%m-%d}")
            for column, label in (
                ("2 Yr", "2-Year"), ("5 Yr", "5-Year"),
                ("10 Yr", "10-Year"), ("30 Yr", "30-Year"),
            ):
                value, change_bps = yields[column]
                lines.append(
                    f"🔹 {label}: {value:.2f}% "
                    f"({format_change(change_bps, unit='bps', decimals=0)})"
                )
    except Exception as e:
        print(f"Treasury yields failed: {e}")
        lines.append("Treasury yields unavailable")

    lines.extend(["", "💱 Currency Pairs"])
    add_quote("💶 EUR/USD", "EURUSD=X", "{:.5f}")
    add_quote("💷 GBP/USD", "GBPUSD=X", "{:.5f}")
    lines.extend([
        "",
    ])
    return "\n".join(lines)


def summarize_news(articles):    
    headlines = "\n\n".join(
        f"""Title: {article['title']}
Summary: {article['summary']}
URL: {article['link']}"""
        for article in articles
    )

    prompt = f"""
You are a professional global macroeconomic news editor writing for a Telegram audience of students and finance enthusiasts.

Task:
- Read all provided articles (Title, Summary, URL).
- Group them into thematic sections.
- Select only the most important and market-moving stories.
- Merge duplicate stories from different sources into one concise story.
- Ignore low-impact, local, entertainment, lifestyle, promotional, repetitive, and non-economic news.

Newsworthiness Rules:

Prioritize factual, event-driven news.

Prefer stories reporting:
- Official economic data releases (CPI, PPI, GDP, PMI, employment, retail sales, etc.)
- Central bank decisions or speeches that moved markets
- Government policy announcements
- Major corporate earnings
- Mergers & acquisitions
- Trade policy, tariffs, sanctions
- Significant geopolitical developments affecting financial markets
- Major moves in financial markets, commodities, or crypto

Avoid:
- Opinion articles
- Editorials
- Commentary
- Explainers
- Long-form features
- Lifestyle pieces
- Generic "trend" articles
- Speculative forecasts without a new catalyst

Only include an analysis article if it explains a major market-moving event that occurred today and there is no stronger factual story available.

Before selecting a story, ask:
"Would Bloomberg or Reuters likely consider this one of today's important market headlines?"
If the answer is no, skip it.

For the Macroeconomy section, prioritize in this order:
1. Inflation
2. Employment
3. GDP
4. PMI
5. Retail Sales
6. Manufacturing
7. Consumer Confidence
8. Fiscal Policy

Avoid broad opinion pieces discussing long-term economic trends unless they are based on newly released official data.

Prioritize these sections:

🌍 Macroeconomy
🏦 Central Banks & Interest Rates
📈 Financial Markets
₿ Crypto & Digital Assets
🛢️ Energy & Commodities
🤖 Corporate & Global Industry
⚠️ Geopolitics (only if market-relevant)

Rules:
- Each section should include a maximum of 1–2 stories.
- Skip sections with no important news.
- Do NOT force stories into sections.
- Merge duplicate coverage from multiple sources.
- Prefer official reporting over commentary.
- Prefer Reuters, Bloomberg, Financial Times, Wall Street Journal and official releases when multiple sources report the same story.

URL RULES (IMPORTANT):

- First, select all news and structure the briefing normally.
- AFTER selection, decide which stories deserve a link.

Link inclusion rules:
- Include URLs for ONLY 2–4 stories in the entire report.
- Prioritize linking:
  • Most important macro story
  • One major markets or central bank story
  • One geopolitical or energy story (if highly relevant)
- Do NOT attach URLs to every story.
- Do NOT reduce the number of stories because of URL rules.
- Keep story selection and URL selection as separate steps.
- Never output a URL whose domain is ft.com. If a selected story only has an ft.com link available, do not include a source link for that story.

When adding a URL:
- Place it under the story as:
  🔗 Source
  <URL>



Output format:

🌍 Global Economic News 💰📈

🌍 Macroeconomy
1. Story title + 1–2 relevant emojis
Short explanation (2–3 sentences including key figures when available)
🔗 Read more:
<URL>

🏦 Central Banks & Interest Rates
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

📈 Financial Markets
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

₿ Crypto & Digital Assets
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

🛢️ Energy & Commodities
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

🤖 Corporate & Global Industry
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

⚠️ Geopolitics
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

📌 Market Summary:
Write 2–3 sentences connecting the most important stories above.

-Explain:
 - How the reported events are related to each other (if there is a connection)
 - How they influenced different markets or investor sentiment
 - The main economic implication investors should pay attention to
-Rules:
 -Do not introduce new information that was not mentioned in the selected stories.
 -If the stories are unrelated, summarize the key market themes separately.

📚 Daily Econ Word (Education Bonus):
- Select ONE intermediate or advanced economic or financial term that appears naturally in today's selected news.
- The purpose is to teach readers a concept they are unlikely to already know well.
- Before choosing a term, ask yourself:
  "Would a second-year economics student already be familiar with this term?"
  If yes, continue looking for a more educational term.
- Avoid choosing basic terms such as:
  GDP, CPI, PPI, inflation, deflation, recession, tariff, interest rates, employment, unemployment, stocks, bonds, oil, gold, Bitcoin, cryptocurrency, exports, imports, trade, central bank, Federal Reserve, ECB.
- Prefer richer concepts such as:
  Yield curve, Carry trade, Repo market, Quantitative easing, Quantitative tightening, Credit spread, Risk premium, Core inflation, Stagflation, Disinflation, Capital flight, Safe-haven asset, Shadow banking, Currency peg, Contango, Backwardation, Moral hazard, Liquidity trap, Soft landing, Hard landing.
- Explain the term simply in 2–3 sentences.
- Whenever possible, relate the explanation to one of today's selected news stories.
- Make the explanation intuitive rather than textbook-like.


Rules:
- Keep total output between 200 and 250 words (excluding URLs).
- Use clear, professional English.
- Do NOT invent facts or numbers.
- Base explanations only on the provided articles.
- If multiple articles cover the same event, combine them into one story.
- Each story should use different emojis.
-Emoji rules (IMPORTANT):
  - Use 1–2 emojis in every headline. 
  - Choose emojis that match the specific story, company, event, or concept—not just the section.
  - Avoid repeating the same emoji combinations across different stories.
  - Prefer descriptive emojis that help readers instantly recognize the topic (e.g. 🏦 for banks, 🛢️ for oil, 🥇 for gold, 🤝 for mergers, 🏭 for manufacturing, 🗳️ for elections, 🚢 for shipping, 💻 for semiconductors, 📊 for ETFs).
  - Every emoji should have a purpose, not just decoration.
- Telegram formatting rules (IMPORTANT):
  - Do NOT use any Markdown formatting.
  - Do NOT use asterisks (*) anywhere in the output.
  - Do NOT bold, italicize, or underline any text.
  - Output plain text only.
- Do not include URLs for stories that were not selected.
- If a selected story is primarily analysis rather than factual reporting, label it as:
  📝 Analysis
  before its explanation.

Make the final result feel like a Bloomberg Morning Brief or Reuters Market Wrap: concise, factual, highly newsworthy, and easy to skim.

Headlines:
{headlines}
"""

    client = genai.Client(api_key=GEMINI_KEY)
    
    primary_model = "gemini-3.5-flash"
    backup_model = "gemini-2.5-flash"
    max_retries = 3
    delay = 2  # wait 2 seconds initially

    # --- Try generating with the newer Gemini 3.5 Flash first ---
    for attempt in range(max_retries):
        try:
            print(f"Attempting econ summary with {primary_model} (Attempt {attempt + 1}/{max_retries})...")
            response = client.models.generate_content(
                model=primary_model,
                contents=prompt
            )
            return response.text
            
        except APIError as e:
            if e.code == 503:
                print(f"Gemini 3.5 is busy (503). Retrying in {delay} seconds...")
                time.sleep(delay)
                delay *= 2  # Exponential backoff
            else:
                # If it is any other type of API error (like 400 or 403), raise it
                raise e
        except Exception as e:
            print(f"Connection issue on attempt {attempt + 1}: {e}. Retrying...")
            time.sleep(delay)
            delay *= 2

    # --- Fallback Option ---
    # If Gemini 3.5 was completely overloaded, we use your highly reliable Gemini 2.5 Flash
    print(f"Gemini 3.5 was unavailable. Falling back to the highly reliable {backup_model}...")
    try:
        response = client.models.generate_content(
            model=backup_model,
            contents=prompt
        )
        return response.text
    except Exception as fallback_err:
        return f"Gemini Error: Both {primary_model} and {backup_model} failed. Details: {fallback_err}"


def split_telegram_message(message, limit=4000):
    """Keep each part below Telegram's limit, including supplementary emojis."""
    chunks = []
    while message:
        units = 0
        end = 0
        for char in message:
            size = 2 if ord(char) > 0xFFFF else 1
            if units + size > limit:
                break
            units += size
            end += 1
        if end == 0:
            raise ValueError("Message limit is too small")
        if end < len(message):
            # Prefer paragraph, then line boundaries to keep stories readable.
            boundary = message.rfind("\n\n", 0, end)
            if boundary > 0:
                end = boundary + 2
            else:
                boundary = message.rfind("\n", 0, end)
                if boundary > 0:
                    end = boundary + 1
        chunks.append(message[:end])
        message = message[end:]
    return chunks


def send_to_telegram(message):
    primary_chat_id = (CHANNEL_ID or "").strip()
    secondary_chat_id = (CHANNEL_ID_2 or "").strip()
    if not primary_chat_id:
        raise ValueError("CHANNEL_ID is required. Set it in GitHub Actions secrets.")

    destinations = [("CHANNEL_ID", primary_chat_id)]
    if secondary_chat_id:
        destinations.append(("CHANNEL_ID_2", secondary_chat_id))
    else:
        print("CHANNEL_ID_2 is not set; skipping the optional second channel.")

    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    parts = split_telegram_message(message)

    for channel_name, chat_id in destinations:
        for index, part in enumerate(parts):
            if index:
                time.sleep(1)
            result = requests.post(
                url,
                json={"chat_id": chat_id, "text": part},
                timeout=30,
            )
            data = result.json()
            if not result.ok or not data.get("ok"):
                raise RuntimeError(
                    f"Telegram send to {channel_name} failed: "
                    f"{data.get('description', 'Unknown error')}"
                )
            print(f"Sent part {index + 1}/{len(parts)} to {channel_name}")


def main():
    print("Getting news...")

    articles = get_news()

    print(f"Found {len(articles)} articles")

    summary = summarize_news(articles)

    snapshot = get_market_snapshot()

    final_message = f"""{summary}

{snapshot}"""

    print("Summary created")

    send_to_telegram(final_message)

    print("Posted to Telegram")


if __name__ == "__main__":
    main()
