# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl40BzMlcMXK6rvf8BEMSb-go66h0v2z
"""

import os
import feedparser
import requests
from google import genai


# Get secrets from GitHub Actions
BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_ID = os.getenv("CHANNEL_ID")
GEMINI_KEY = os.getenv("GEMINI_KEY")
ALPHA_VANTAGE_KEY = os.getenv("ALPHA_VANTAGE_KEY")


RSS_FEEDS = [
    "https://feeds.marketwatch.com/marketwatch/topstories/",
    "https://www.coindesk.com/arc/outboundfeeds/rss/",
    "https://www.investing.com/rss/news.rss",
    "https://feeds.reuters.com/reuters/businessNews",
    "https://feeds.reuters.com/reuters/globalmarketsNews",

    # Added feeds
    "https://www.ft.com/rss/home",
    "https://oilprice.com/rss/main",
    "https://cointelegraph.com/rss",
    "https://www.imf.org/en/News/RSS",
]


def get_news():
    articles = []

    for feed_url in RSS_FEEDS:
        try:
            feed = feedparser.parse(feed_url)

            if not hasattr(feed, "entries"):
                continue

            for entry in feed.entries[:3]:
                if hasattr(entry, "title") and hasattr(entry, "link"):
                    articles.append({
                        "title": entry.title,
                        "link": entry.link
                    })

        except Exception as e:
            print(f"RSS failed: {feed_url} -> {e}")

    return articles

import requests

def get_market_data():

    # 🟡 GOLD
    gold = requests.get(
        "https://api.metals.live/v1/spot/gold"
    ).json()
    gold_price = gold[0]["price"]

    # 🛢️ OIL (WTI Crude)
    oil = requests.get(
        "https://stooq.com/q/l/?s=cl.f&f=sd2t2ohlcv&h&e=json"
    ).json()
    wti_price = oil["symbols"][0]["close"]

    # ₿ CRYPTO (Bitcoin + Ethereum + Solana)
    crypto = requests.get(
        "https://api.coingecko.com/api/v3/simple/price",
        params={
            "ids": "bitcoin,ethereum,solana",
            "vs_currencies": "usd"
        }
    ).json()

    btc_price = crypto["bitcoin"]["usd"]
    eth_price = crypto["ethereum"]["usd"]
    sol_price = crypto["solana"]["usd"]

    return {
        "gold_price": gold_price,
        "wti_price": wti_price,

        "btc_price": btc_price,
        "eth_price": eth_price,
        "sol_price": sol_price
    }

def summarize_news(articles, market_data):
    headlines = "\n".join(
        f"- {article['title']}"
        for article in articles
    )

    prompt = f"""
You are a professional global macroeconomic news editor writing for a Telegram audience of students and finance enthusiasts.

Task:
- Read all provided headlines.
- Select the 5 most important global macroeconomic and financial stories of the day.
- Prioritize: inflation, GDP, central banks, interest rates, stock markets, oil/energy, crypto, major corporate events.
- Ignore low-impact, local, entertainment, and repetitive news.

Output format:

🌍 Global Economic News 💰📈

1. Title of story + 1–2 relevant emojis only
Short but informative explanation (2–4 sentences). Include key numbers (percentages, prices, rates) if available.

2. Title of story + 1–2 relevant emojis only
Short explanation (2–4 sentences) with context and impact on markets/economy.

3. Title of story + 1–2 relevant emojis only
Short explanation (2–4 sentences).

4. Title of story + 1–2 relevant emojis only
Short explanation (2–4 sentences).

5. Title of story + 1–2 relevant emojis only
Short explanation (2–4 sentences).

📌 Market Summary:
Write 2–3 sentences summarizing the overall global market mood (risk-on / risk-off), and what investors should watch next (rates, inflation, geopolitics, crypto, etc.).

📊 Live Market Snapshot:

Gold: {market_data['gold_price']}
Oil (WTI): {market_data['wti_price']}
Bitcoin: {market_data['btc_price']}
Ethereum: {market_data['eth_price']}
Solana: {market_data['sol_price']}


Rules:
- Maximum 200 words total.
- Clear, professional English (not too academic, not casual).
- Use numbers when available.
- Do NOT invent data.
- If multiple headlines describe the same event, merge them into one point.
- Each story MUST use different emojis (do not repeat emojis across stories).
- Emojis must match meaning of the topic:
  - Inflation / macro → 📊📈💹
  - Central banks / rates → 🏦💰
  - Stocks / markets → 📉📈💼
  - Crypto → ₿🚀🪙
  - Oil / energy → 🛢️⚡
  - Risk / uncertainty → ⚠️🌍
  - Tech / companies → 🤖💻🚀
- Avoid meaningless or random emojis like 🤯 unless absolutely necessary.

Make it feel like a Bloomberg-style daily briefing for Telegram.

Headlines:
{headlines}
"""

    client = genai.Client(api_key=GEMINI_KEY)

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

def send_to_telegram(message):

    url = (
        f"https://api.telegram.org/"
        f"bot{BOT_TOKEN}/sendMessage"
    )

    payload = {
        "chat_id": CHANNEL_ID,
        "text": message
    }

    result = requests.post(
        url,
        json=payload
    )

    print(result.json())


def main():

    print("Getting news...")

    articles = get_news()

    print(f"Found {len(articles)} articles")

    market_data = get_market_data()

    summary = summarize_news(articles, market_data)
    print("Summary created")

    send_to_telegram(summary)

    print("Posted to Telegram")


if __name__ == "__main__":
    main()
