# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl40BzMlcMXK6rvf8BEMSb-go66h0v2z
"""

import os
import feedparser
import requests
from google import genai


# Get secrets from GitHub Actions
BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_ID = os.getenv("CHANNEL_ID")
GEMINI_KEY = os.getenv("GEMINI_KEY")
CHANNEL_ID_2 = os.getenv("CHANNEL_ID_2")


RSS_FEEDS = [
    # 📊 MarketWatch (official RSS)
    "https://feeds.marketwatch.com/marketwatch/topstories/",

    # ₿ CoinDesk (crypto)
    "https://www.coindesk.com/arc/outboundfeeds/rss/",

    # 📈 Investing.com (official RSS)
    "https://www.investing.com/rss/news.rss",
    "https://www.investing.com/rss/news_25.rss",  # economic calendar / macro focus

    # 📰 Reuters (official but limited RSS)
    "https://feeds.reuters.com/reuters/businessNews",
    "https://feeds.reuters.com/reuters/globalmarketsNews",

    # 📊 Yahoo Finance (official RSS)
    "https://finance.yahoo.com/news/rssindex",
    "https://feeds.finance.yahoo.com/rss/2.0/headline",

    # 🏦 Financial Times (official section RSS)
    "https://www.ft.com/world?format=rss",
    "https://www.ft.com/markets?format=rss",
    "https://www.ft.com/global-economy?format=rss",

    # 🏛 Bloomberg (⚠️ via Google News RSS workaround)
    "https://news.google.com/rss/search?q=site:bloomberg.com+markets",
    "https://news.google.com/rss/search?q=site:bloomberg.com+economy",

    # 📰 Wall Street Journal (⚠️ limited + workaround)
    "https://wsj.com/xml/rss/3_7014.xml",
    "https://wsj.com/xml/rss/3_7031.xml",
    "https://news.google.com/rss/search?q=site:wsj.com+markets",

    # 📊 Morningstar (no official RSS → Google News workaround)
    "https://news.google.com/rss/search?q=site:morningstar.com+stocks",
    "https://news.google.com/rss/search?q=site:morningstar.com+fund",

    # 📉 Barron's (no official RSS → workaround)
    "https://news.google.com/rss/search?q=site:barrons.com+markets",

    # 🌍 The Economist (no official RSS → workaround)
    "https://news.google.com/rss/search?q=site:economist.com+economy"
]


def get_news():
    articles = []

    for feed_url in RSS_FEEDS:
        try:
            feed = feedparser.parse(feed_url)

            if not hasattr(feed, "entries"):
                continue

            for entry in feed.entries[:3]:
                if hasattr(entry, "title") and hasattr(entry, "link"):
                    articles.append({
                        "title": entry.title,
                        "summary": getattr(entry, "summary", ""),
                        "link": entry.link
                    })

        except Exception as e:
            print(f"RSS failed: {feed_url} -> {e}")

    return articles

def summarize_news(articles):

    headlines = "\n\n".join(
        f"""Title: {article['title']}
    Summary: {article['summary']}
    URL: {article['link']}"""
        for article in articles
    )

    prompt = f"""
You are a professional global macroeconomic news editor writing for a Telegram audience of students and finance enthusiasts.

Task:
- Read all provided articles (Title, Summary, URL).
- Group them into thematic sections.
- Select only the most important and market-moving stories.
- Merge duplicate stories from different sources into one concise story.
- Ignore low-impact, local, entertainment, lifestyle, promotional, repetitive, and non-economic news.

Newsworthiness Rules:

Prioritize factual, event-driven news.

Prefer stories reporting:
- Official economic data releases (CPI, PPI, GDP, PMI, employment, retail sales, etc.)
- Central bank decisions or speeches that moved markets
- Government policy announcements
- Major corporate earnings
- Mergers & acquisitions
- Trade policy, tariffs, sanctions
- Significant geopolitical developments affecting financial markets
- Major moves in financial markets, commodities, or crypto

Avoid:
- Opinion articles
- Editorials
- Commentary
- Explainers
- Long-form features
- Lifestyle pieces
- Generic "trend" articles
- Speculative forecasts without a new catalyst

Only include an analysis article if it explains a major market-moving event that occurred today and there is no stronger factual story available.

Before selecting a story, ask:
"Would Bloomberg or Reuters likely consider this one of today's important market headlines?"
If the answer is no, skip it.

For the Macroeconomy section, prioritize in this order:
1. Inflation
2. Employment
3. GDP
4. PMI
5. Retail Sales
6. Manufacturing
7. Consumer Confidence
8. Fiscal Policy

Avoid broad opinion pieces discussing long-term economic trends unless they are based on newly released official data.

Prioritize these sections:

🌍 Macroeconomy
🏦 Central Banks & Interest Rates
📈 Financial Markets
₿ Crypto & Digital Assets
🛢️ Energy & Commodities
🤖 Corporate & Global Industry
⚠️ Geopolitics (only if market-relevant)

Rules:
- Each section should include a maximum of 1–2 stories.
- Skip sections with no important news.
- Do NOT force stories into sections.
- Merge duplicate coverage from multiple sources.
- Prefer official reporting over commentary.
- Prefer Reuters, Bloomberg, Financial Times, Wall Street Journal and official releases when multiple sources report the same story.

Output format:

🌍 Global Economic News 💰📈

🌍 Macroeconomy
1. Story title + 1–2 relevant emojis
Short explanation (2–3 sentences including key figures when available)
🔗 Read more:
<URL>

🏦 Central Banks & Interest Rates
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

📈 Financial Markets
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

₿ Crypto & Digital Assets
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

🛢️ Energy & Commodities
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

🤖 Corporate & Global Industry
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

⚠️ Geopolitics
1. Story title + 1–2 relevant emojis
Short explanation
🔗 Read more:
<URL>

📌 Market Summary:
Write 2–3 sentences summarizing:
- Overall market mood (risk-on / risk-off)
- Cross-asset behavior
- What investors should watch next

📚 Daily Econ Word (Education Bonus):
- Select ONE economic or financial term directly related to today's news.
- Explain it simply in 2–3 sentences.
- Make it intuitive rather than textbook-like.

Rules:
- Keep total output between 200 and 250 words (excluding URLs).
- Use clear, professional English.
- Do NOT invent facts or numbers.
- Base explanations only on the provided articles.
- If multiple articles cover the same event, combine them into one story.
- Each story should use different emojis.
- Emojis should match the topic:
  - Macro → 📊📈💹
  - Rates → 🏦💰
  - Markets → 📉📈💼
  - Crypto → ₿🚀🪙
  - Energy → 🛢️⚡
  - Geopolitics → ⚠️🌍
  - Corporate → 🤖💻🚀
- Telegram formatting rule: Do NOT use double asterisks (**). Use single asterisks (*) only for bold.
- Do not include URLs for stories that were not selected.
- If a selected story is primarily analysis rather than factual reporting, label it as:
  📝 Analysis
  before its explanation.

Make the final result feel like a Bloomberg Morning Brief or Reuters Market Wrap: concise, factual, highly newsworthy, and easy to skim.

Headlines:
{headlines}
"""

    client = genai.Client(api_key=GEMINI_KEY)

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

def send_to_telegram(message):

    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

    for chat_id in [CHANNEL_ID, CHANNEL_ID_2]:

        payload = {
            "chat_id": chat_id,
            "text": message
        }

        result = requests.post(
            url,
            json=payload
        )

        print(result.json())


def main():

    print("Getting news...")

    articles = get_news()

    print(f"Found {len(articles)} articles")

    summary = summarize_news(articles)

    print("Summary created")

    send_to_telegram(summary)

    print("Posted to Telegram")


if __name__ == "__main__":
    main()
